Iter13
NStegura/metrics pull request #13
Opened 2023-12-12 17:13 UTC by NStegura

2023-12-13 16:18 UTC, s-shpak requested changes

2023-12-13 16:18 UTC, s-shpak commented on internal/app/metricsapi/server.go
> +	timeout = 1 * time.Second
Кажется, что это очень короткий таймаут, особенно в контексте потенциальных ретраев

2023-12-13 16:18 UTC, s-shpak commented on internal/app/metricsapi/server.go
> +			w.WriteHeader(http.StatusInternalServerError)
Стоит также залогировать ошибку

2023-12-13 16:18 UTC, s-shpak commented on internal/app/metricsapi/server_test.go
> +	r, _ := repo.New(ctx, "", 100, "", false, l)
В тестах ошибки также стоит проверять

2023-12-13 16:18 UTC, s-shpak commented on internal/clients/metric/client.go
>  		URL:    fmt.Sprintf("http://%s", url),
А что если в `url` уже есть схема?

2023-12-13 16:18 UTC, s-shpak commented on internal/clients/metric/client.go
> +		return fmt.Errorf("failed to parse metrics, err %w", err)
Здесь ты не парсишь, а наоборот кодируешь объект в строку

2023-12-13 16:18 UTC, s-shpak commented on internal/clients/metric/client.go
> +		_ = resp.Body.Close()
Эту ошибку можно залогировать

2023-12-13 16:18 UTC, s-shpak commented on internal/clients/metric/client.go
> +func (c *client) requestLogger(req *http.Request) (resp *http.Response, err error) {
Мне не очень нравится этот дизайн: логгирование и отправление запросов - два независимых события, лучше не помещать их в одну функцию. Если ты сделал это, т.к. оборачиваешь это действие в логику `backoff`, то лучше назвать этот метод `do`, чтобы было ясно, что именно здесь запрос отправляется на сервер

2023-12-13 16:18 UTC, s-shpak commented on internal/clients/metric/client.go
> +	for _, backoff := range c.sheduleBackoffAttempts() {
Почему бы не использовать https://github.com/hashicorp/go-retryablehttp ?

2023-12-13 16:18 UTC, s-shpak commented on internal/repo/internal/db/db.go
> +func (db *DB) Init(ctx context.Context) error {
Зачем разделять эту логику и конструктор?

2023-12-13 16:18 UTC, s-shpak commented on internal/repo/internal/db/db.go
> +		db.logger.Errorf("CreateCounterMetric failed, %s", err)
Можем ли мы продолжать выполнение здесь после ошибки?

2023-12-13 16:18 UTC, s-shpak commented on internal/repo/internal/db/db.go
> +		db.logger.Debugf("GetGaugeMetric failed, %s", err)
Почему эта ошибка логируется на уровне `Debug`, кажется, что мы хотели бы видеть ее в любом случае

2023-12-13 16:18 UTC, s-shpak commented on internal/repo/internal/db/db.go
> +func (db *DB) createHistoryMetric(ctx context.Context, mType string, name string, value interface{}) {
Если ты делаешь два запроса к базе в рамках одной операции, то их надо оборачивать в транзакцию

2023-12-13 16:18 UTC, s-shpak commented on internal/repo/internal/mem/memrepo.go
> +func (r *InMemoryRepo) UpdateGaugeMetric(ctx context.Context, name string, value float64) error {
В Go если ты не используешь аргумент, а добавляешь его только для соответствия интерфейсу, аргумент принято называть `_`

2023-12-13 18:48 UTC, NStegura commented on internal/clients/metric/client.go
>  		URL:    fmt.Sprintf("http://%s", url),
Как минимум странно, тк я управляю энвами и все же использовать `u, err := url.Parse("metrics-api:8082")` не вариант, тк для него `metrics-api - схема` автоматом становится
Тут либо в энвах делить на хост/порт, либо в них же передавать одной строкой со схемой
Есть вариант сделать через `net.SplitHostPort()`, потом это привести к `*Url ` но тоже костыльно получается, а если там схема есть

2023-12-13 18:49 UTC, NStegura commented on internal/clients/metric/client.go
>  		URL:    fmt.Sprintf("http://%s", url),
В общем, не придумал, как красиво это сделать

2023-12-13 20:53 UTC, NStegura commented on internal/repo/internal/db/db.go
> +func (db *DB) Init(ctx context.Context) error {
Кажется, что в конструкторе должно быть все самое необходимое, а логика с запуском миграций или по запуску бэкапа - немного другой процесс (и не должен быть скрыт), вынес в итоге при инициализации в общий New с интерфейсом

2023-12-22 18:40 UTC, NStegura commented on internal/app/metricsapi/server.go
> +	timeout = 1 * time.Second
почему?
секунда на апдейт в базу - это уже жирно

2023-12-23 12:20 UTC, NStegura commented on internal/clients/metric/client.go
> +	for _, backoff := range c.sheduleBackoffAttempts() {
Не успеваю посмотреть, если не блок, то заменю на январских

2023-12-24 16:35 UTC, s-shpak commented on internal/app/metricsapi/server.go
> +	timeout = 1 * time.Second
Предположим, что это жирно. Тем не менее, представим, что ты столкнулся с тем, что некоторые запросы требуются больше времени чем 1 секунда (например, потому что возникли какие-то проблемы с сетью). Является ли это поводом завершать запросы с ошибкой ?

2023-12-24 16:42 UTC, s-shpak commented on internal/clients/metric/client.go
>  		URL:    fmt.Sprintf("http://%s", url),
А если пока использовать `url` без какой-либо дополнительной обработки ? Ломаются автотесты ?

2023-12-24 16:45 UTC, s-shpak commented on internal/repo/internal/db/db.go
> +func (db *DB) Init(ctx context.Context) error {
Текущий дизайн требует от пользователя `db` вызов конструктора и вызов `Init`. Что если пользователь забудет вызвать `Init` ? Я не вижу проблемы в установлении соединения при конструировании объекта, т.к. предполагается, что соединение с БД будет открыто все время до завершения приложения

2023-12-24 16:51 UTC, s-shpak requested changes

2023-12-24 16:51 UTC, s-shpak commented on internal/repo/internal/db/db.go
> +	db.logger.Debugf("Save counter metric failed, %v", ID)
Это случайно скопированый код ?

2023-12-24 16:51 UTC, s-shpak commented on internal/clients/metric/client.go
> +	if err != nil {
Любая ли ошибка должна приводить к retry ?

2023-12-24 16:51 UTC, s-shpak commented on internal/clients/metric/client.go
> +	resp, err = c.DoWithLog(req)
Может можно как-то переписать код, чтобы не вызывать `DoWithLog` 2 раза ?

2023-12-24 16:51 UTC, s-shpak commented on internal/repo/repository.go
> +	GetAllMetrics(ctx context.Context) ([]models.GaugeMetric, []models.CounterMetric)
Почему `GetAllMetrics` не возвращает ошибку ?

2023-12-24 16:51 UTC, s-shpak commented on internal/repo/internal/db/db.go
> +func (db *DB) Init(ctx context.Context) error {
Я вижу, что ты убрал `Init`, так что коммент можно зарезолвить

2023-12-24 16:54 UTC, NStegura commented on internal/app/metricsapi/server.go
> +	timeout = 1 * time.Second
Скорее всего таймаут отстрелит уже на стороне клиента, но для сервера разницы нет, можно и увеличить

2023-12-24 17:03 UTC, NStegura commented on internal/clients/metric/client.go
>  		URL:    fmt.Sprintf("http://%s", url),
Немного запутался, если передавать тут не через `fmt.Sprintf("http://%s", url)`, то ругается `unsupported protocol scheme \"metrics-api\""`
Если я допом не валидирую, то как мне понять есть ли схема или нет

2023-12-24 17:06 UTC, NStegura commented on internal/repo/internal/db/db.go
> +	db.logger.Debugf("Save counter metric failed, %v", ID)
Ошибся в логе, поправил

2023-12-24 19:12 UTC, NStegura commented on internal/clients/metric/client.go
> +	if err != nil {
Переписал, смотрю теперь на Status Code

2023-12-25 15:05 UTC, s-shpak commented on internal/clients/metric/client.go
>  		URL:    fmt.Sprintf("http://%s", url),
Могу порекомендовать только вызывать `url.Parse` в начале программы и проверить поле `Scheme`. Если оно отличается от `http` или `https`, то добавить схему с помощью https://pkg.go.dev/net/url#JoinPath (как здесь https://go.dev/play/p/_ND_TkRxAjK)

2023-12-25 15:15 UTC, s-shpak requested changes

2023-12-25 15:15 UTC, s-shpak commented on internal/clients/metric/client.go
> +		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
Ошибка 4** также не должна приводить к ретраю - она говорит о том, что запрос пользователя не может быть обработан, потому что с самим запросом что-то не так. По сути, повторять запрос мы должны только в случае внутренней ошибки сервиса

2023-12-25 15:15 UTC, s-shpak commented on internal/repo/internal/db/db.go
> +		db.logger.Errorf("GetAllMetrics failed, %s", err)
Если ошибка теперь возвращаетс, то не стоит ее логировать здесь

2023-12-25 19:54 UTC, NStegura commented on internal/clients/metric/client.go
>  		URL:    fmt.Sprintf("http://%s", url),
поправил в 14 Пре

2023-12-25 21:03 UTC, s-shpak approved these changes

2023-12-25 21:22 UTC, merged