Iter15
NStegura/metrics pull request #15
Opened 2024-01-10 11:45 UTC by NStegura

2024-01-11 18:09 UTC, s-shpak requested changes
В целом все хорошо. Я забыл, мы с тобой обсуждали добавление `.golangci-lint` в `.gitignore` ? Если коротко, то его надо пушить в репозиторий. Если ты хочешь убрать использование каких-то линтеров, то стоит просто отредактировать этот файл конфигурации: дефолтный конфиг ловит мало проблем -- например, он пропустил то, что ты не проверил ошибку

2024-01-11 18:09 UTC, s-shpak commented on internal/app/agent/agent.go
> +	maxErrsCount := 2
Не понятно, зачем контроллировать количество ошибок: лучше либо позволять ошибкам случатья и логировать их, либо нет. Внедрять какое-то пороговое значение для ошибок кажется лишним. К тому же неясно зачем это значение постоянно возвращать из функции: во-первых, оно константное; во-вторых, кажется, что не функция должна определять это пороговое значение

2024-01-11 18:09 UTC, s-shpak commented on internal/app/agent/agent.go
> +	for w := 1; w <= ag.config.RateLimit; w++ {
А что если значение < 1 ?

2024-01-11 18:09 UTC, s-shpak commented on internal/app/metricsapi/hashvalidationmiddleware.go
Используй `_` или `-` для разделения слов в именах файлов

2024-01-11 18:09 UTC, s-shpak commented on internal/app/metricsapi/hashvalidationmiddleware.go
> +				w.WriteHeader(http.StatusInternalServerError)
Ошибки в случае `InternalServerError` лучше логировать, т.к. это неожиданные ошибки, о которых лучше узнавать

2024-01-11 18:09 UTC, s-shpak commented on internal/clients/metric/client.go
> +func (c *Client) UpdateMetrics(metrics []Metrics, compressType string) error {
Лучше не добавлять `compressType` в сигнатуру: как правило ты никогда не будешь использовать разные типы сжатия в рамках одной сессии клиента. Потому лучше инкапсулировать такие детали и не позволять их динамически параметризовывать

2024-01-11 18:09 UTC, s-shpak commented on internal/clients/metric/client.go
> +		h.Write(body)
Ошибку над проверять

2024-01-12 15:15 UTC, NStegura commented on internal/app/agent/agent.go
> +	for w := 1; w <= ag.config.RateLimit; w++ {
тут непонятно, стоит такое ограничивать (валидировать) на уровне получения конфига? (так и сделаю)

2024-01-14 14:42 UTC, s-shpak requested changes

2024-01-14 14:42 UTC, s-shpak commented on internal/app/agent/agent.go
> +		for range reportTicker.C {
Я не обратил на это внимание в прошлом ревью, но это важно.

Не очень хорошо, что в воркер попадает логика выбора момента для отправления сообщения: воркер должен только выполнять работу, которую ему присылают. Потому хорошо было бы:
1. убрать тикер в диспетчер: как только тик прилетает, диспетчер пытается запистаь в канал джоб новый набор метрик
2. свободный воркер подхватывает его из канала и обрабатывает
3. если свободного воркера нет, то можно дропнуть задачу и залогировать факт этого

2024-01-14 16:08 UTC, NStegura commented on internal/app/agent/agent.go
> +		for range reportTicker.C {
Пришлось смотреть на cap и len и cap каналов

2024-01-15 13:09 UTC, s-shpak requested changes

2024-01-15 13:09 UTC, s-shpak commented on internal/app/agent/agent.go
> +		for range reportTicker.C {
Это слишком сложно, можно упростить. Тебе точно не надо смотерть на заполненность канала: чтобы скипнуть запись метрики в заполненный канал достаточно воспользоваться такой конструкцией:

```go
select {
case jobs <- metricsPack:
    ....
default:
    log.Println("failed to send metrics: all workers are busy")
}
```

То есть тебе будет достаточно:
1. собирать метрики по тику
2. писать их в какую-то конкурентно безопасную структуру (возможно перезаписывая предыдущий сбор, в ТЗ не указано, что их нельзя терять)
3. по другому тику пытаться передать собранную метрику в канал джоб
4. если воркер не может подхватить ее, просто залогировать факт этого и продолжить выполнение программы

Что-то типа: https://go.dev/play/p/_Ia2QnRdizj

2024-01-15 13:27 UTC, NStegura commented on internal/app/agent/agent.go
> +		for range reportTicker.C {
Сейчас часть кода поправлю, но мне хочется добиться такого результата
Метрики складываются по тику разными способами (пытаются не теряться, может там апи отвалилось, значит делаю буфер)
Далее все эти метрики пытаются отправиться в джобы и если они не справляются -> скип

То есть мне все равно придется сделать так

```
		for range reportTicker.C {
			ag.logger.Info("add jobs tick")
			for len(metricsPollCh) > 0 {
				metrics := <-metricsPollCh
				select {
				case jobs <- metrics:
					ag.logger.Info("add job metric")
				default:
					ag.logger.Info("skip job")
				}
			}
```

Иначе по тику будет отправляться только одна (понимаю, что в тз этого нет, но это ему и не противоречит)
Так бы я сделал в рабочем решении, если бы хотел хоть как-то обезопасить себя от недоступности сервиса 
 и сохранить историю, при этом не сильно нагрузив апи и не сильно засорив MEM агента

2024-01-15 13:28 UTC, NStegura commented on internal/app/agent/agent.go
> +		for range reportTicker.C {
Ссылка https://go.dev/play/p/_Ia2QnRdizj выдала `Cannot load shared snippet; try again.`

2024-01-15 13:29 UTC, NStegura commented on internal/app/agent/agent.go
> +		for range reportTicker.C {
Еще есть момент о котором я думал, идея в тз - не нагружать апи, тут семафор лучше бы зашел

2024-01-17 12:55 UTC, s-shpak requested changes

2024-01-17 12:55 UTC, s-shpak commented on internal/app/agent/agent.go
> +	bufferCount := 10
Как получено это значение ?

2024-01-17 12:55 UTC, s-shpak commented on internal/app/agent/agent.go
> +		for range reportTicker.C {
Я бы не советовал тебе так делать, но если очень хочется, то ок.

В этом случае необходимо убедиться, что сбор метрик независим от отправки метрик. Также необходимо ограничит размер буфера для хранения метрик и удостовериться, что новые метрики будут вытеснять старые, если буфер переполняется

2024-01-26 17:57 UTC, NStegura commented on internal/app/agent/agent.go
> +	bufferCount := 10
поправил

2024-01-29 18:48 UTC, s-shpak approved these changes

2024-02-03 14:51 UTC, merged