Iter18
NStegura/metrics pull request #17
Opened 2024-03-08 20:19 UTC by NStegura

2024-03-09 20:17 UTC, s-shpak requested changes
Сейчас покртыие тестами составляет 10.5 % (я считаю так, как описано здесь: https://stackoverflow.com/questions/33444968/how-to-get-all-packages-code-coverage-together-in-go). В этом спринте требуется достичь 40 %. Надо рассчитывать по-другому, или тестов действительно не хватает ?

2024-03-10 17:22 UTC, NStegura commented
![image](https://github.com/NStegura/metrics/assets/73823012/efd3fcdb-706f-4f4f-ac6c-189990b05cf9)

2024-03-10 17:22 UTC, NStegura commented
сделай make cover (убрал easyjson)

2024-03-10 20:53 UTC, s-shpak requested changes
Тебе стоит также убрать моки из покрытия.

При запуске на своей машине, получаю покрытие в 28.3%, посмотрим, пожалуйста, что именно считается некорректно (cover.out прикладываю
[cover.zip](https://github.com/NStegura/metrics/files/14551767/cover.zip)
)

2024-03-12 20:27 UTC, merged