Iter23
NStegura/metrics pull request #21
Opened 2024-08-29 20:52 UTC by NStegura

2024-09-02 13:43 UTC, nburunova requested changes

2024-09-02 13:43 UTC, nburunova commented on config/agent_config.go
> +	MetricCliKey        string         `json:"metric_cli_key"`
не понимаю,что означает этот ключ, давай подберём более говорящее название

2024-09-02 13:43 UTC, nburunova commented on config/agent_config.go
> +	PublicCryptoKeyPath string         `json:"crypto_key"`
зачем в конфиге параметры и ключа и пути к файлу с ключом? Давай оставим только путь к файлу, в задании только такое требование

2024-09-02 13:43 UTC, nburunova commented on config/server_config.go
> +	PrivateCryptoKeyPath string          `json:"crypto_key"`
давай тут тоже только path оставим в настройках.

2024-09-02 13:43 UTC, nburunova commented on config/server_config.go
> +	RequestKey           string          `json:"request_key"`
не очень говорящее название

2024-09-02 13:43 UTC, nburunova commented on cmd/server/main.go
>  func runRest() error {
агент нужно тоже прерывать по syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT.

2024-09-02 13:43 UTC, nburunova commented on internal/app/metricsapi/decrypt_middleware.go
> +func (s *APIServer) decryptMiddleware(h http.Handler) http.Handler {
сюда можно вторым аргументом передать логгер и логировать им ошибку на 26 строке

2024-09-13 20:04 UTC, Bazys requested changes
у тебя в го.млд версия 1.22
metric := metric
такое в циклах лишнее теперь
и есть парочка мелких вопросов

2024-09-13 20:04 UTC, Bazys commented on internal/app/agent/agent.go
>  		var counter int64 = 0
инт при инициализации = 0, нет смысла явно указывать, мв не в JS, тут нет undefined

2024-09-13 20:04 UTC, Bazys commented on cmd/server/main.go
> +	"github.com/NStegura/metrics/config"
импорты не до конца отсортированы
твои пакеты должны быть последнимим

2024-09-14 09:19 UTC, NStegura commented
если убрать metric := metric - ругается линтер, проверил, что он работает по версии в go.mod
` range-val-address: suspicious assignment of 'metric'. range-loop variables always have the same address (revive) `
аппрувни плз, чтобы я новый ПР создал по следующей задаче и если есть предложение как поправить - оставь коммент
я еще погуглю как это попрпавить и в след пр занесу

2024-09-16 06:50 UTC, merged