iter5
NStegura/metrics pull request #5
Opened 2023-11-08 00:18 UTC by NStegura

2023-11-08 15:18 UTC, s-shpak requested changes

2023-11-08 15:18 UTC, s-shpak commented on Makefile
> +.PHONY:
Почему ты оставил `.PHONY` пустым?

2023-11-08 15:18 UTC, s-shpak commented on cmd/server/main.go
> +	"github.com/NStegura/metrics/internal/bll"
Что делают пакеты `bll` и `dll` ? Их стоит назвать как-то более понятно

2023-11-08 15:18 UTC, s-shpak commented on cmd/server/main.go
> +	runRest()
Я бы советовал тебе вызывать Fatal в main, а из runRest вернуть ошибку

2023-11-08 15:18 UTC, s-shpak commented on go.mod
Необходимо обновить `go.mod`

2023-11-08 15:18 UTC, s-shpak commented on Makefile
В Makefile можно добавить target, чтобы собирать сразу оба компонента

2023-11-08 15:18 UTC, s-shpak commented on internal/app/agent/agent.go
> +	metrics.GaugeMetrics[Alloc] = &models.GaugeMetric{Name: Alloc, Type: Gauge, Value: float64(stats.Alloc)}
Почему бы не создать мапу, где ключем будет название метрики, а значением - значение из `stats`, и заполнить мапу в `metrics`, скопировав в нее значения из первой мапы?

2023-11-08 15:18 UTC, s-shpak commented on internal/app/agent/agent.go
> +	gaugeMetrics := make(map[models.MetricName]*models.GaugeMetric)
Здесь мы знаем количество элементов в мапе, его можно указать при инициализации

2023-11-08 15:18 UTC, s-shpak commented on internal/app/agent/agent.go
> +			time.Sleep(time.Second * time.Duration(ag.config.PollInterval))
Я бы советовал тебе возвращать Duration из config, а не вычислять его здесь. В этом случае сложнее ошибиться, если в будущем ты решишь поменять размерность

2023-11-08 15:18 UTC, s-shpak commented on internal/app/agent/agent.go
> +		logger: logrus.New(),
Обычно логгер инджектится извне

2023-11-08 15:18 UTC, s-shpak commented on internal/app/agent/config.go
> +		c.ReportInterval, _ = strconv.Atoi(report)
Ошибки надо проверять

2023-11-08 15:18 UTC, s-shpak commented on internal/app/metricsapi/server.go
> +			body += fmt.Sprintf("%s: %v\r\n", m.Name, m.Value)
Я бы использовал `strings.Builder` здесь

2023-11-08 15:18 UTC, s-shpak commented on internal/app/metricsapi/server.go
> +		if errors.Is(err, customerrors.ErrNotFound) {
А если произошла какая-то другая ошибка?

2023-11-08 15:18 UTC, s-shpak commented on internal/bll/bll.go
> +	_, err = bll.repo.GetGaugeMetric(gmReq.Name)
Добавь везде логику о том, что произойдет, если ошибка будет другой

2023-11-12 13:26 UTC, NStegura commented on internal/app/agent/agent.go
> +	metrics.GaugeMetrics[Alloc] = &models.GaugeMetric{Name: Alloc, Type: Gauge, Value: float64(stats.Alloc)}
так сделал, потому что не хотел делать мапу с типом значений пустого интерфейса, вряд ли будут еще другого типа метрики

те вместо 
```
type Metrics struct {
	GaugeMetrics   map[MetricName]*GaugeMetric
	CounterMetrics map[MetricName]*CounterMetric
}

```
получится 

`map[string]interface{}`

2023-11-12 13:27 UTC, NStegura commented on internal/app/agent/agent.go
> +	metrics.GaugeMetrics[Alloc] = &models.GaugeMetric{Name: Alloc, Type: Gauge, Value: float64(stats.Alloc)}
но если вдруг они появятся и придется вносить еще - будет определенно резон тут передать

2023-11-12 13:46 UTC, NStegura commented on internal/app/agent/agent.go
> +			time.Sleep(time.Second * time.Duration(ag.config.PollInterval))
хотел сделать через flag.Duration(), но там ругались тесты
поэтому немного костыльну в самом конфиге

2023-11-12 14:46 UTC, NStegura commented on Makefile
> +.PHONY:
поправил

2023-11-12 14:46 UTC, NStegura commented on cmd/server/main.go
> +	"github.com/NStegura/metrics/internal/bll"
переименовал

2023-11-13 18:57 UTC, s-shpak requested changes

2023-11-13 18:57 UTC, s-shpak commented on cmd/agent/main.go
> +		log.Fatal(err)
А здесь фаталиться можно уже с использованием логгера

2023-11-13 18:57 UTC, s-shpak commented on internal/app/metricsapi/business.go
> +type Bll interface {
Зачем объявлять интерфейс в отдельном файле? объяви его лучше там, где он используется

2023-11-13 18:57 UTC, s-shpak commented on internal/app/metricsapi/server.go
> +			} else {
Этот (и подобные) else не нужен

2023-11-13 23:10 UTC, NStegura commented on internal/app/metricsapi/business.go
> +type Bll interface {
Так он же тут и используется?
Куда его двинуть, в internal/app/metricsapi/server.go?
Но почему бы его не оставить в отдельном файле, пакет же общий

2023-11-15 20:52 UTC, s-shpak commented on internal/app/metricsapi/business.go
> +type Bll interface {
В Go , как правило, все пишется максимально близко к месту использования. Например, в этом случае, будет понятнее кем и как испольуется интерфейс, если он будет определен рядом с местом использования. Это минорная проблема, потому зачет, если захочешь - поменяй

2023-11-15 20:52 UTC, s-shpak approved these changes

2023-11-17 12:26 UTC, merged