iter9
NStegura/metrics pull request #9
Opened 2023-11-28 20:25 UTC by NStegura

2023-11-30 11:50 UTC, s-shpak requested changes
Необходимо добавить `golangci-lint` как для локального запуска, так и для `github actions`. Инструкции здесь: https://github.com/s-shpak/praktikum-golangci-lint

2023-11-30 11:50 UTC, s-shpak commented on cmd/server/main.go
> +	signal.Notify(sigs, os.Interrupt, syscall.SIGTERM)
Лучше используй `NotifyContext`

2023-11-30 11:50 UTC, s-shpak commented on cmd/server/main.go
> +		logger.Fatal(sig)
Кажется, что процесс не должен завершаться с ошибкой в случае получения `os.Interrupt`, например, потому не стоит использовать Fatal так

Кроме того процесс надо завершать в основной горутине

2023-11-30 11:50 UTC, s-shpak commented on internal/app/agent/agent.go
> +	Gauge   models.MetricType = "gauge"
Если эти константы используются только в этом пакете, они не должны быть экспортируемыми

2023-11-30 11:50 UTC, s-shpak commented on internal/app/agent/agent.go
> +				ag.logger.Fatal(err)
Фаталиться в глубине кода нельзя. Кроме того не надо вообще прекращать выполнение программы, если метрику нельзя обработать: лучше залогировать ошику и продолжить

2023-11-30 11:50 UTC, s-shpak commented on internal/app/metricsapi/gzipmiddleware.go
> +func (c *compressWriter) Header() http.Header {
Если ты добавиь `http.ResponseWriter` в `compressWriter` через композицию, тебе не надо будет явно определять эти методы

2023-11-30 11:50 UTC, s-shpak commented on internal/app/metricsapi/server.go
> +	return http.ListenAndServe(s.config.BindAddr, s.requestLogger(s.gzipMiddleware(s.router)))
middleware лучше добавить при помощи `router.Use()`

2023-11-30 11:50 UTC, s-shpak commented on cmd/server/main.go
> +	r := repo.New(
Мне не очень нравится, как организован код репозитория. Лучше будет сделать так:
1. должно быть два типа `in-memory store` и `file store`. С т.з. уровня бизне-логики их поведение никак не отличается (то есть все различия инкапсулированы)
2. `file store` - по сути обертка над `in-memory store`, которая добавляет периодическое сохранение на диск. То есть дублировать логику `in-memory store` в `file store` не нужно, `file store` должен расширять `in-memory store`.
3. инициализация нужного объекта происходит здесь и зависит от параметров конфигурации

2023-11-30 11:50 UTC, s-shpak commented on internal/repo/backup.go
> +func (r *repository) MakeBackup() error {
Все методы, которые используются в том же пакете, где они определены, не должны экспортироваться

2023-12-08 13:45 UTC, NStegura commented on internal/app/metricsapi/gzipmiddleware.go
> +			return count, io.EOF
из-за линтера пришлось вернуть EOF
он буквально не дает вернуть просто err, даже если мы уже знаем, что это именно ошибка конца файла
а если вернуть через fmt, то это не работает как задумано

немного посмотрел что происходит при ReadRequest из библиотеки (они буквально сравнивают через == ошибки)

```
func readRequest(b *bufio.Reader) (req *Request, err error) {
	tp := newTextprotoReader(b)
	defer putTextprotoReader(tp)

	req = new(Request)

	// First line: GET /index.html HTTP/1.0
	var s string
	if s, err = tp.ReadLine(); err != nil {
		return nil, err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
```

2023-12-08 14:29 UTC, s-shpak commented on cmd/server/main.go
> +	signal.Notify(sigs, os.Interrupt, syscall.SIGTERM)
После добавления `NotifyContext` канал `sigs` не нужен

2023-12-08 14:29 UTC, s-shpak commented on internal/app/metricsapi/gzipmiddleware.go
> +func (c *compressWriter) Header() http.Header {
Это пока не сделано

2023-12-08 14:31 UTC, s-shpak requested changes
Добавь меня, пожалуйста, в контрибьюторы, чтобы я мог закрывать комменты

2023-12-08 15:32 UTC, s-shpak approved these changes

2023-12-09 17:44 UTC, merged